name: Build Docker Image and Deploy to GCP

on:
  push:
    branches: [main]
  workflow_dispatch:
    
jobs:
  build_and_deploy:
    permissions: 
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: food-data-express
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      PORT_IMAGE: 8080
    steps:
      - uses : actions/checkout@v3

      - name : Create .env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo IMAGE_URL=${{ vars.IMAGE_URL }} >> .env

      - id : auth
        name : Authenticate to Google Cloud
        uses : google-github-actions/auth@v1
        with :
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
  
      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE_NAME }} .
  
      - name: Configure Docker Client
        run: |
          gcloud auth configure-docker --quiet
  
      - name: Push Image
        run: |
          docker tag ${{ env.IMAGE_NAME }} asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
          docker push asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}
    
      - id: 'deploy'
        name: 'Deploy to Cloudrun'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: ${{ env.IMAGE_NAME }}
          image: asia.gcr.io/${{ env.PROJECT_ID }}/${{ env.IMAGE_NAME }}:latest
          region: asia-southeast1
          flags: '--allow-unauthenticated --port=${{ env.PORT_IMAGE }} --max-instances=10'
          
      - name: 'Deploy URL'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
